Repository F4ntasticFour/EasyTrip, pull requests merged in 2023-12, with the labels that each got.

#15 Passenger Class Implementation
  BusClass.cpp
  BusClass.h
  CMakeLists.txt
  CompanyClass.cpp
  LinkedList.h
  LinkedList.impl
  Node.h
  Node.impl
  PassengerClass.cpp
  PassengerClass.h
  StationClass.cpp
  StationClass.h
Labels: good first issue, Dev

#19 Additions to Bus and Passengers Classes.
  BusClass.h
  CompanyClass.cpp
  CompanyClass.h
  EventClass.h
  PassengerClass.cpp
  PassengerClass.h
  StationClass.cpp
  StationClass.h
  main
Labels: bug

#24 Project wide integration of Classes
  BusClass.cpp
  BusClass.h
  CMakeLists.txt
  CompanyClass.cpp
  CompanyClass.h
  EventClass.cpp
  EventClass.h
  LinkedList.h
  PassengerClass.cpp
  PassengerClass.h
  PriorityQueue.h
  main.cpp
Labels: bug, FileHandling, Dev

#25 File Handler
  FileHandler.cpp
  FileHandler.h
  StationClass.h
Labels: Dev

#28 Issue 43
  .DS_Store
  CompanyClass.cpp
  CompanyClass.h
  EventClass.cpp
  EventClass.h
  FileHandler.cpp
  FileHandler.h
  LinkedList.h
  PassengerClass.cpp
  PassengerClass.h
  Stack.h
  StationClass.cpp
  StationClass.h
  random_file.txt
Labels: bug, Dev
